### ISSUE TITLE
Download link?

### ISSUE THREAD

**Issue by ShitijHalder** [Magisk-Modules-Alt-Repo/gamingmode#3]
.

**Comment by swilger** [comment]
same

**Comment by Barak182** [comment]
Hallow

**Comment by mcd2525** [comment]
Ok

**Comment by P15328** [comment]
> Liên kết tải xuống ở đâu? Bất kỳ bản phát hành !?

**Comment by SectionTN** [comment]
switch to desktop mode in browser and download the zip, open it and extract the folder, zip the files in folder (not the folder or you'll get unzip error in magisk) and flash it

**Comment by Sahmul1919** [comment]
#3

**Comment by ghost** [comment]
Going into desktop mode and downloading as a zip then trying to install doesn't work. It throws a unzip error which is bullshit.

**Comment by SectionTN** [comment]
@TheSpecialist666 Hello
![Screenshot_20220712-215759_Magisk.png](https://user-images.githubusercontent.com/73752904/178594465-fde3880b-881d-464a-9217-dd95c9395509.png)
i've fixed the module, here's the zip that you need to flash [gaming.zip](https://ufile.io/jt9vwgpd)
